### ISSUE TITLE
Keys property are not working with custom mapping

### ISSUE THREAD

**Issue by rajivduseja** [PredixDev/px-breadcrumbs#16]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior:
Custom mappings of properties should work with keys property specified.

## Actual Behavior:
When added custom mapping breadcrumb is not populating values on UI.

## Steps to reproduce the problem:
Update the mapping as per below example:-
 keys='{"id":"uri","label":"label","children":"children","icon":"icon"}'

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Windows 10, Chrome

## Screenshots (_optional, but very helpful_):
![breadcrumbs_error](https://user-images.githubusercontent.com/6428475/33720763-fc52ae4e-db8a-11e7-9206-903ec6dad9f0.PNG)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
Once you've created your code example, you can save it under a new url.
Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

<px-breadcrumbs keys='{"id":"uri","label":"label","children":"children","icon":"icon"}' items='[{"uri":"uri 1","label":"label 1","children":[{"uri":"uri A 1","label":"label A 1"},{"uri":"uri A 2","label":"label A 2"}]},{"uri":"uri 2","label":"label 3"},{"uri":"uri 4","label":"label 4"},{"uri":"uri 5","label":"label 6"},{"uri":"uri 7","label":"label 8"}]'
    selected-route='["uri 1"]'></px-breadcrumbs>

**Comment by davidrleonard** [comment]
Confirmed. This CodePen reproduces the problem: https://codepen.io/davidleonard/pen/rYEYoO?editors=1001

We're statically calling `item.id` in a few places in px-breadcrumbs instead of looking up the custom key for `id`.

Here: https://github.com/PredixDev/px-breadcrumbs/blob/e489300364ed40010ede771dbc66018659474d8b/px-breadcrumbs.es6.js#L451-L453

Also here: 

https://github.com/PredixDev/px-breadcrumbs/blob/e489300364ed40010ede771dbc66018659474d8b/px-breadcrumbs.es6.js#L499-L501

There are quite a few other places where we use `item.label` or `item.children`, etc., without looking up the custom key. We also need to update those to get the appropriate custom key.

**Comment by davidrleonard** [comment]
Fixed as of v1.1.1
